codecov:
  notify:
    require_ci_to_pass: true
  coverage:
    precision: 2
    round: down
    range: "70...100"
  comment:
    layout: "header, diff, changes, footer"
    behavior: default
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags: auto