version: "3.9"
services:
  back-prod:
    depends_on:
      - mongo
    networks:
      - amis-precieux-back # Connecte ce service au réseau "tp-docker-back"
    container_name: back-prod
    image: back:prod
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.amisprecieux.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  mongo:
    networks:
      - amis-precieux-back
    image: mongodb/mongodb-community-server:latest
    volumes:
      - mongo-prod-data:/data/db # Volume persistante pour les données de MongoDB.

# Définition du volume pour les données MongoDB.
volumes:
  mongo-prod-data:

# Définition du réseaux
networks:
    amis-precieux-back: