name: deploy api

on:
  push:
    branches:
    - main
  
jobs:        
    
  main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy repository
      uses: actions/checkout@v3

    - name: 'Create env file'
      run: |
        touch .env
        echo JWT=${{ secrets.JWT }} >> .env

    - name: Copy file via ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: 22
        key: ${{ secrets.KEY }}
        source: "."
        target: api

    - name: deploy api
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        script: sudo docker compose -f api/docker-compose-prod.yml up --build -d